name: CI/CD for Yii2 Docker App

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest .

    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.HOST_SSH_KEY }}
        script: |
          docker service update --image ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest yii2-service
